# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Match Dev"
  lane :match_development do
    puts 'APP_ID:' + ENV['FASTLANE_APP_ID']
    match(type: 'development', readonly: true)
  end

  desc "Match Test"
  lane :match_adhoc do
    puts 'APP_ID:' + ENV['FASTLANE_APP_ID']
    match(type: 'adhoc', readonly: true)
  end

  desc "Pem"
  lane :pem_gen do
    puts 'APP_ID:' + ENV['FASTLANE_APP_ID']
    pem(development: true)
  end
end
